# Домашнее задание "Линейная алгебра. Матрицы".
## Уровень 0:
### Задание 1
Создайте матрицу 3 на 3, заполненную числами от 1 до 9
- Прибавьте к ней матрицу с единицами на диагонале
- Умножьте полученную матрицу на вектор (1, 2, 3)
- Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
- Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [31]:
import numpy as np

In [32]:
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Телефонная матрица
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A2 = A1 + np.eye(3) #Прибавляем матрицу с единицами по диагонали
A2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [34]:
A3 = A2.dot(np.array([1, 2, 3])) #Умножаем на вектор
A3

array([15., 34., 53.])

In [35]:
np.transpose(A2) #Транспонированная матрица

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [36]:
A4 = np.linalg.inv(A2) #Обратная матрица
A4

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

Проверяем - является ли матрица A4 обратной матрицы A2

In [37]:
np.linalg.matrix_rank(A2)

3

In [38]:
np.linalg.matrix_rank(A4)

3

## Уровень 1:
### Задание 2
Найдите собственные значения и собственные вектора матрицы:

In [40]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [44]:
values, vectors = np.linalg.eig(m)

In [48]:
values #Собственные значения матрицы

array([1., 4.])

In [55]:
result = np.transpose(vectors) #Собственные векторы матрицы
result

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

Преобразуем вектора для удобства вычислений

In [56]:
result[0] / 0.4472136 

array([-1.99999998,  0.99999999])

In [57]:
result[1] / -0.70710678

array([1., 1.])

### Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [68]:
det = 0

while det != 1:
    a = np.random.randint(-10,10,(3,3))
    det=np.linalg.det(a)
    
print('искомая матрица: \n',a)

искомая матрица: 
 [[ 8  8 -3]
 [ 1  2  4]
 [-6 -7 -2]]
